-- Active: 1689829705174@@127.0.0.1@3306@mess

CREATE TABLE
    Student(
        ID VARCHAR(15) NOT NULL PRIMARY KEY COMMENT 'Primary Key',
        ADMIN_ID VARCHAR(15) UNIQUE COMMENT 'Managing the mess',
        NAME VARCHAR(255),
        TOKEN_VALIDITY DATE,
        PASSWORD VARCHAR(15) NOT NULL,
        TODAY_BREAKFAST BOOLEAN DEFAULT False,
        TODAY_LUNCH BOOLEAN DEFAULT False,
        TODAY_DINNER BOOLEAN DEFAULT False
    );

CREATE TABLE
    ADMIN(
        ADMIN_ID VARCHAR(15) NOT NULL PRIMARY KEY,
        PASSWORD VARCHAR(15) NOT NULL,
        STUDENT_COUNT INTEGER
    );

CREATE TABLE
    EVENTS(
        EVENT_ID VARCHAR(15) NOT NULL PRIMARY KEY,
        EVENT_NAME VARCHAR(30)
    );

CREATE TABLE
    BREAKFAST(
        BREAKFAST_ID VARCHAR(15) PRIMARY KEY,
        HAS_RICE BOOLEAN,
        HAS_CHAPATTI BOOLEAN,
        VEGETABLE VARCHAR(25),
        DESSERT VARCHAR(20),
        FRUITS VARCHAR(25)
    );

CREATE TABLE
    LUNCH(
        LUNCH_ID VARCHAR(15) PRIMARY KEY,
        HAS_RICE BOOLEAN,
        HAS_CHAPATTI BOOLEAN,
        VEGETABLE VARCHAR(25),
        DESSERT VARCHAR(20),
        FRUITS VARCHAR(25)
    );

CREATE TABLE
    DINNER(
        DINNER_ID VARCHAR(15) PRIMARY KEY,
        HAS_RICE BOOLEAN,
        HAS_CHAPATTI BOOLEAN,
        VEGETABLE VARCHAR(25),
        DESSERT VARCHAR(20),
        FRUITS VARCHAR(25)
    );

CREATE TABLE
    TODAY_FOOD(
        EVENT_ID VARCHAR(15) NOT NULL,
        ADMIN_ID VARCHAR(15) PRIMARY KEY,
        BREAKFAST_ID VARCHAR(15) NOT NULL,
        LUNCH_ID VARCHAR(15) NOT NULL,
        DINNER_ID VARCHAR(15) NOT NULL
    );

CREATE TABLE
    PREVIOUS_DATA(
        EVENT_ID VARCHAR(15) NOT NULL,
        DATE DATE PRIMARY KEY,
        ADMIN_ID VARCHAR(15) NOT NULL,
        BREAKFAST_ID VARCHAR(15) NOT NULL,
        LUNCH_ID VARCHAR(15) NOT NULL,
        DINNER_ID VARCHAR(15) NOT NULL
    );